---
deployment:
  tasks:
    - export DEPLOYPATH=/home/casevals/public_html/website_7d06a396
    - /bin/cp -R images $DEPLOYPATH/
    - /bin/cp -R css $DEPLOYPATH/
    - /bin/cp -R js $DEPLOYPATH/
    - /bin/cp -R services $DEPLOYPATH/
    - /bin/cp -R locations $DEPLOYPATH/
    - /bin/cp -R blog $DEPLOYPATH/
    - /bin/cp -R about $DEPLOYPATH/
    - /bin/cp -R contact $DEPLOYPATH/
    - /bin/cp -R privacy $DEPLOYPATH/
    - /bin/cp index.html $DEPLOYPATH/
    - /bin/cp robots.txt $DEPLOYPATH/
    - /bin/cp sitemap.xml $DEPLOYPATH/
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
